sudo: false
language: c
addons:
  apt:
    packages:
      - libgstreamer0.10-dev
      - libgstreamer-plugins-base0.10-dev
      - libgsl0-dev
      - libcairo2-dev
compiler:
 - clang
 - gcc
before_script:
 - ./autogen.sh
script: make
